/*
==============================================================
Purpose: Creating SnowPipe for Integration of Data from GCS
==============================================================
*/

USE DATAWAREHOUSE;
USE SCHEMA BRONZE;

-- 1. Create Snowpipe for CRM Customer Info
CREATE OR REPLACE PIPE DATAWAREHOUSE.BRONZE.PIPE_CRM_CUST_INFO
  AUTO_INGEST = TRUE
  INTEGRATION = gcs_notify_init
  AS
  COPY INTO DATAWAREHOUSE.BRONZE.CRM_CUST_INFO
  FROM @DATAWAREHOUSE.BRONZE.GCS_CRM_STAGE
  PATTERN = '.*cust_info.*\.csv'
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FILE_FORMAT = (FORMAT_NAME= DATAWAREHOUSE.BRONZE.CSV_FILE_FORMAT);

-- 2. Create Snowpipe for CRM Product Info
CREATE OR REPLACE PIPE DATAWAREHOUSE.BRONZE.PIPE_CRM_PRD_INFO
  AUTO_INGEST = TRUE
  INTEGRATION = gcs_notify_init
  AS
  COPY INTO DATAWAREHOUSE.BRONZE.CRM_PRD_INFO
  FROM @DATAWAREHOUSE.BRONZE.GCS_CRM_STAGE
  PATTERN = '.*prd_info.*\.csv'
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FILE_FORMAT = (FORMAT_NAME= DATAWAREHOUSE.BRONZE.CSV_FILE_FORMAT);

-- 3. Create Snowpipe for CRM Sales Details
CREATE OR REPLACE PIPE DATAWAREHOUSE.BRONZE.PIPE_CRM_SALES_DETAILS
  AUTO_INGEST = TRUE
  INTEGRATION = gcs_notify_init
  AS
  COPY INTO DATAWAREHOUSE.BRONZE.CRM_SALES_DETAILS
  FROM @DATAWAREHOUSE.BRONZE.GCS_CRM_STAGE
  PATTERN = '.*sales_details.*\.csv'
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FILE_FORMAT = (FORMAT_NAME = DATAWAREHOUSE.BRONZE.CSV_FILE_FORMAT);
  
-- 4. Create Snowpipe for ERP Customer Info
CREATE OR REPLACE PIPE DATAWAREHOUSE.BRONZE.PIPE_ERP_CUST_AZ12
  AUTO_INGEST = TRUE
  INTEGRATION = gcs_notify_init
  AS
  COPY INTO DATAWAREHOUSE.BRONZE.ERP_CUST_AZ12
  FROM @DATAWAREHOUSE.BRONZE.GCS_ERP_STAGE
  PATTERN = '.*CUST_AZ12.*\.csv'
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FILE_FORMAT = (FORMAT_NAME = DATAWAREHOUSE.BRONZE.CSV_FILE_FORMAT);

-- 5. Create Snowpipe for ERP Location Info
CREATE OR REPLACE PIPE DATAWAREHOUSE.BRONZE.PIPE_ERP_LOC_A101
  AUTO_INGEST = TRUE
  INTEGRATION = gcs_notify_init
  AS
  COPY INTO DATAWAREHOUSE.BRONZE.ERP_LOC_A101
  FROM @DATAWAREHOUSE.BRONZE.GCS_ERP_STAGE
  PATTERN = '.*LOC_A101.*\.csv'
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FILE_FORMAT = (FORMAT_NAME = DATAWAREHOUSE.BRONZE.CSV_FILE_FORMAT);

-- 6. Create Snowpipe for ERP Product Category Info
CREATE OR REPLACE PIPE DATAWAREHOUSE.BRONZE.PIPE_ERP_PX_CAT_G1V2
  AUTO_INGEST = TRUE
  INTEGRATION = gcs_notify_init
  AS
  COPY INTO DATAWAREHOUSE.BRONZE.ERP_PX_CAT_G1V2
  FROM @DATAWAREHOUSE.BRONZE.GCS_ERP_STAGE
  PATTERN = '.*PX_CAT_G1V2.*\.csv'
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FILE_FORMAT = (FORMAT_NAME = DATAWAREHOUSE.BRONZE.CSV_FILE_FORMAT);

SHOW PIPES IN SCHEMA DATAWAREHOUSE.BRONZE;
